__author__ = 'fzhang'
# Configure the module according to your needs
import os, sys
import time


def get_last_file_mtime():
    """
    get the latest file in a dir/list and return its mtime in epochseconds
    :return:epochseconds
    """
    return time.time()


def main():
    from datadog import initialize
    from datadog import api  # Use Datadog REST API client

    options = {
        'api_key': '1d563',
        'app_key': 'd125e'
    }

    initialize(**options)

    hostname = os.uname()[1]
    runuser = os.environ['USER']

    title = "Event generated by Python code: " + sys.argv[0]
    text = 'From host= %s runuser=%s' % (hostname, runuser)
    tags = ['version:1', 'PythonApp']

    api.Event.create(title=title, text=text, tags=tags)

if __name__=="__main__":

    THRESHOLD=2*60*60

    lastfile_mtime=get_last_file_mtime()

    time.sleep(10)

    now=time.time()



    print now

    difftime= now- lastfile_mtime

    print difftime

    if difftime>THRESHOLD:
        main()