__author__ = 'fzhang'
# Configure the module according to your needs
from datadog import initialize

options = {
     'api_key':'1d563c78bee1119c899f8084bc4d57d6',
     'app_key':'d125ef1bf2cc3d65fd28aed4a53dc4b6a7be116a'
}

initialize(**options)

 # Use Datadog REST API client
from datadog import api
import os,  sys

hostname= os.uname()[1]
runuser= os.environ['USER']


title = "Event generated by Python code: " + sys.argv[0]
text = 'From host= %s runuser=%s' %(hostname, runuser)
tags = ['version:1', 'PythonApp']

api.Event.create(title=title, text=text, tags=tags)

